blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/ItsLhuis/Tunno#readme
    about: Check the documentation first
  - name: ðŸ’¬ Discussions
    url: https://github.com/ItsLhuis/Tunno/discussions
    about: Ask questions or discuss ideas
